name: compile
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: stevenwdv/setup-fasm@v1
      - uses: actions/checkout@v1
      - name: Create slam executable
        run: |
          sudo cp $(which fasm) /usr/bin/fasm
          ./old/slam.py -i lib -o slam slam.slm
          rm output.*
          ./slam -i lib -o slam slam.slm
          ./slam -v
          cd tests
          ../slam -i ../lib -o test test.slm
          ./test
