name: compile
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  test-slam:
    runs-on: ubuntu-latest
    steps:
      - uses: stevenwdv/setup-fasm@v1
      - name: Create slam executable
        id: compile
        run: |
          sudo cp $(which fasm) /usr/bin/fasm
          git clone http://github.com/slam-lang/spakig
          cd spakig
          chmod +x ./install.sh
          ./install.sh
          cd ..
      - name: Run slam tests
        id: tests
        run: |
          git clone http://github.com/slam-lang/slam
          cd slam
          make test >> $GITHUB_STEP_SUMMARY
