name: compile
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: stevenwdv/setup-fasm@v1
      - uses: actions/checkout@v1
      - name: Create slim executable
        run: |
          sudo cp $(which fasm) /usr/bin/fasm
          ./old/slim.py -i lib -o slim slim.slm
          rm output.*
          ./slim -i lib -o slim slim.slm
          ./slim -v
          cd tests
          ../slim -i ../lib -o test test.slm
          ./test
