name: compile
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: stevenwdv/setup-fasm@v1
      - name: Create slam executable
        run: |
          sudo cp $(which fasm) /usr/bin/fasm
          git clone http://github.com/slam-lang/spakig
          cd spakig
          fasm -m 524288 spakig.fasm temp.o
          ld -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o ./spakig -lc -melf_x86_64 temp.o
          ./spakig init
          cd ..
          git clone http://github.com/slam-lang/slam
          cd slam/tests
          ~/.local/slam/bin/slam -o test test.slm
          ./test
